<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SkillSwapAPI.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkillSwapAPI.Application\SkillSwapAPI.Application.csproj" />
    <ProjectReference Include="..\SkillSwapAPI.Infrastructure\SkillSwapAPI.Infrastructure.csproj" />
  </ItemGroup>
</Project>
